# The config file for the model
train_model:  # train the model
    data_id: '1'
    data_name: sv_cograph0  # sv_textgraph/sv_cograph0-11
    model_name: GIN  # GCN, GraphSAGE, GIN, TAGCN
    NOISE_RATIO: 0.0
    NUM_EPOCHS: 500
    is_trainable: True
    GPU: -1  # 0/1